// Generated by scripts/generate-eco-data.mjs — do not edit manually.
// @ts-ignore - imported as text via esbuild loader
import rawTsv from "./eco-data.tsv";

export interface EcoEntry { eco: string; name: string; pgn: string; epd: string; }

export const ECO_DATA: EcoEntry[] = (rawTsv as string).trim().split("\n").map(line => {
	const [eco, name, pgn, epd] = line.split("\t");
	return { eco, name, pgn, epd };
});
